# Generated by Django 5.0.3 on 2024-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_evento_actividad_alter_evento_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='acotaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='especialista_uare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='previsto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
