# Generated by Django 5.0.3 on 2024-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_proceso_acotaciones_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
