# Generated by Django 5.0.3 on 2024-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_proceso_descripcion_alter_proceso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='cant_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cant_unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='obtencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
