# Generated by Django 5.0.3 on 2024-09-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_proceso_cant_items_proceso_cant_unidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'unique_together': {('tipo', 'nombre')},
            },
        ),
    ]
