# Generated by Django 5.0.3 on 2024-09-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'verbose_name': 'Proceso', 'verbose_name_plural': 'Procesos'},
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='acotaciones_adicionales',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='cant_items',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='cant_unidades',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='especialista_uare',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='obtencion',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='previsto',
        ),
        migrations.AddField(
            model_name='proceso',
            name='cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proceso',
            name='convocado',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='proceso',
            name='convocatoria',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proceso',
            name='derivado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='expediente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='moneda',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nomenclatura',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='periodo',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='parametro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='pages.parametro'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='acti',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
