# Generated by Django 5.0.3 on 2024-10-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_proceso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='convocado',
            field=models.ForeignKey(limit_choices_to={'parametro_id': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_convocado', to='pages.formula'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='periodo',
            field=models.ForeignKey(limit_choices_to={'parametro_id': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_periodo', to='pages.formula'),
        ),
    ]
